import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="p-6">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="space-y-3">
        <h1 className="text-3xl md:text-6xl mb-6 font-bold">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {['One', 'Two', 'Three'].map(number =>
            <div key={number} className="text-white bg-teal-500 px-2.5 py-1 rounded-lg">
              {number}
            </div>)}
        </div>
      </main>
    </div>
  )
}

export default Home
