import type { NextPage } from 'next'
import Head from 'next/head'
import { joinClasses } from '../utility/css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="space-y-3">
        <h1 className="text-3xl md:text-6xl mb-8 md:mb-24 font-bold">
          Responsive Tailwind demo
        </h1>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {['One', 'Two', 'Three'].map(number =>
            <div
              key={number}
              className={joinClasses([
                'text-white bg-teal-500 px-4 pt-2 pb-4 rounded-lg shadow-lg shadow-teal-500/50',
              ])}
            >
              <div className="mb-3">{number}</div>
              <button
                className="pt-1 pb-1.5 px-4 bg-white text-teal-500 rounded-full -ml-0.5 active:bg-teal-100 active:text-teal-600 active:shadow-lg active:shadow-teal-800/50"
              >
                More Info
              </button>
            </div>)}
        </div>
      </main>
    </>
  )
}

export default Home
